name: Python Simple Addition Function Test

# Trigger the workflow on push or pull request to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose the OS of your choice, e.g., ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python (you can specify the version you need)
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Step 3: Install dependencies (like pytest or unittest)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest  # Install pytest for running tests

      # Step 4: Run the tests using pytest
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Running pytest tests

